name: skolverket_examen
version: 1.0.0
config-version: 2

profile: skolverket_examen

model-paths:
  - dbt_project/staging
  - dbt_project/models
  - dbt_project/marts

analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  skolverket_examen:
    +materialized: table
