name: skolverket_examen
version: "1.0.0"
config-version: 2

profile: skolverket_examen

model-paths: ["models", "staging", "marts"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  skolverket_examen:
    # ریشه‌ی dbt_project/staging/
    staging:
      +materialized: view

    # ریشه‌ی dbt_project/models/
    models:
      silver:
        +materialized: table
      marts:
        +materialized: table

    # ریشه‌ی dbt_project/marts/
    marts:
      +materialized: table
